title: TY Tales
author: Tony Yin
email: t@tonyy.in
description: >  
  TY Tales is a personal blog site discussing topics ranging from products to data to crypto.
logo: /assets/img/logo.png
permalink: /:title/
show_excerpts: false

header_pages:
  - about.md
  - projects.md

google_analytics: UA-51798386-1
disqus:
  shortname: tytales
twitter_username: tonyin
github_username: tonyin
linkedin_username: tonyin
rss: rss

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag