title: Aeto 逸韬
author: Tony Yin
email: t@tonyy.in
description: >
  Public homepage for writings & thoughts
logo: /assets/img/logo.png
permalink: /:title/
show_excerpts: false

header_pages:
  - all.md
  - crypto.md
  - guides.md
  - newsletter.md
  - about.md

google_analytics: UA-51798386-1
disqus:
  shortname: tytales
twitter_username: tonyin
github_username: tonyin
linkedin_username: tonyin
rss: rss

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag